// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0epd7HYVelV_eOhXoW7wswRTYijvzPl0',
    appId: '1:590648779015:web:0f5d6d6532994260c965a2',
    messagingSenderId: '590648779015',
    projectId: 'eureka-8d4b9',
    authDomain: 'eureka-8d4b9.firebaseapp.com',
    storageBucket: 'eureka-8d4b9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtZ-6ugSRaOvutx-zKDgFn3UEf03VONts',
    appId: '1:590648779015:android:f9776593385b7fcac965a2',
    messagingSenderId: '590648779015',
    projectId: 'eureka-8d4b9',
    storageBucket: 'eureka-8d4b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuoHla294brSr0HcAr6O3hkj0zTUdv4Gk',
    appId: '1:590648779015:ios:2e365a3776683b05c965a2',
    messagingSenderId: '590648779015',
    projectId: 'eureka-8d4b9',
    storageBucket: 'eureka-8d4b9.appspot.com',
    iosBundleId: 'fr.cfa.eureka.eureka',
  );
}
